---
title: "Analysis"
author: "Susie and Teddie"
format: pdf
---
Packages: 

```{r}
library(tidyverse)
library(MASS)
library(ordinal)
```


Read in data: 
```{r}
data <- read_csv("ISSP_OECD2015.csv")
data

glimpse(data)
```

Drop rows with missing values, except for ISCO column. (Per PI)
```{r}
data_clean <- data%>%
  tidyr::drop_na()

data_clean1 <- data%>%
  dplyr::select(-isco)%>%
  tidyr::drop_na()

```

## Multilevel ordinal logistic regression
Perform multilevel ordinal logistic regression using polr() function from MASS package.

Response, y = jobsec.  5 level ordinal response. 


```{r}

data_clean1$jobsec <- factor(data_clean1$jobsec, ordered = TRUE, 
                             levels = c("Strongly disagree", "Disagree", "Neither nor", "Agree", "Strongly agree"))

data_clean1$relmgmt <- factor(data_clean1$relmgmt, ordered = F, 
                             levels = c("Very bad", "Quite bad", "Neither nor", "Quite good", "Very good"))


fit <- polr(jobsec~ eprc * relmgmt + unemp +ltu + sex + age + sector + fulltime + union, data = data_clean1)

fit
```

```{r}
summary(fit)
```


```{r}

confint.default(fit)

```
The effect of eprc decreases if you go from neither nor to very good relmt. 


```{r}
#predict(fit, type = "probs")
newdata <- data_clean1[1,]
predict(fit, newdata = newdata, type = "probs")
newdata2 <- newdata
newdata2$relmgmt <- "Very bad"
predict(fit, newdata = newdata2, type = "probs")
newdata2$relmgmt <- "Very good"
predict(fit, newdata = newdata2, type = "probs")


dat <- rbind(newdata, newdata, newdata, newdata, newdata)
dat$relmgmt <- c("Very bad", "Quite bad", "Neither nor", "Quite good", "Very good")
predict(fit, newdata = dat, type = "probs") %>% matplot(type = "b")
```




```{r}

fit0 <- clm(jobsec~ relmgmt + unemp +ltu + sex + age + sector + fulltime + union, data = data_clean1)

fit1 <- clm(jobsec~ eprc + relmgmt + unemp +ltu + sex + age + sector + fulltime + union, data = data_clean1)

fit2 <- clm(jobsec~ eprc * relmgmt + unemp +ltu + sex + age + sector + fulltime + union, data = data_clean1)

summary(fit1)
summary(fit2)

anova(fit0, fit1, fit2)

```




