---
title: "Other notes"
format: pdf
---

## Multilevel ordinal logistic regression
Perform multilevel ordinal logistic regression using polr() function from MASS package.

```{r}
fit <- polr(jobsec~ eprc * relmgmt + unemp +ltu + sex + age + sector + fulltime + union, data = data_clean)

fit
```

```{r}
summary(fit)
```


```{r}

confint.default(fit)

```

The effect of eprc decreases if you go from neither nor to very good relmt. 


```{r}
#predict(fit, type = "probs")
newdata <- data_clean1[1,]
predict(fit, newdata = newdata, type = "probs")
newdata2 <- newdata
newdata2$relmgmt <- "Very bad"
predict(fit, newdata = newdata2, type = "probs")
newdata2$relmgmt <- "Very good"
predict(fit, newdata = newdata2, type = "probs")


dat <- rbind(newdata, newdata, newdata, newdata, newdata)
dat$relmgmt <- c("Very bad", "Quite bad", "Neither nor", "Quite good", "Very good")
predict(fit, newdata = dat, type = "probs") %>% matplot(type = "b")
```

```{r}
library(ggplot2)

ggplot(coef_table, aes(x = OR, y = reorder(term, OR))) +
  geom_point(size = 3, color = "blue") +
  geom_errorbarh(aes(xmin = OR_low, xmax = OR_high), height = 0.2, color = "red") +
  geom_vline(xintercept = 1, linetype = "dashed") +
  scale_x_log10() +
  labs(
    title = "Odds Ratios from Ordinal Logistic Regression (clmm)",
    x = "Odds Ratio (log scale)",
    y = ""
  ) +
  theme_minimal(base_size = 12)
```


```{r}
library(ggplot2)
library(gridExtra)



ggplot(coef_table, aes(y = term, x = OR)) +
  geom_point(shape = 18, size = 2) +  
  geom_errorbarh(aes(xmin = OR_low, xmax = OR_high), height = 0.25) +
  geom_vline(xintercept = 1, color = "red", linetype = "dashed", cex = 1, alpha = 0.5) +
  xlab("Odds Ratio (95% CI)") + 
  ylab(" ") + 
  theme_bw() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.text.x.bottom = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12, colour = "black"))

coef_table

```


